### ISSUE TITLE
Make multiselect fields on datagrid

### ISSUE THREAD

**Issue by anjaleenaren** [hack4impact-upenn/avp#32]
For the fields listed as multiselect on this [sheet](https://docs.google.com/spreadsheets/d/18V8pS_pUQAfvgVtON9rDFk7iI4HyNBqXLYwgAkvAKcM/edit#gid=26024321), maek them multiselect in `client/src/components/DataGrid.tsx`. 

Take a look at the [Mui Datagrid documentaion](https://mui.com/x/api/data-grid/data-grid/). You will need to set the `columnType` of the multiselect fields to a custom type (there is a built in 'singleSelect' type but no multiselect, so you will need to implement this).

**Comment by trangiabach** [comment]
!!![example](https://codesandbox.io/s/columntypesgrid-material-demo-forked-4bbcrv?file=/demo.js:0-3713)!!!!
