### ISSUE TITLE
On the home page, add a button to go to /form

### ISSUE THREAD

**Issue by anjaleenaren** [hack4impact-upenn/avp#66]
From the main page, there should be a button that links to /form. This should not be blocked with an authentication (any user should be able to click the button and go to /form)

[Figma](https://www.figma.com/file/SU5gxYVY8NuyBZJjj9SobQ/AVP?type=design&node-id=5844-16041&mode=design&t=QKTrBfIxBTx8Qos4-0)

**Comment by vszammit** [comment]
can we close this issue?
